import { useQuery } from '@tanstack/react-query';
import { adminApi } from '../utils/api';
import { FileText, Download, Calendar, ArrowRight, Loader2 } from 'lucide-react';
import { format } from 'date-fns';

export default function InvoicesPage() {
  const { data, isLoading, isError } = useQuery({
    queryKey: ['admin-b2b-invoices'],
    queryFn: () => adminApi.getB2BInvoices({ limit: 50 }),
  });

  const handleDownload = async (id: string, invoiceNumber: string) => {
    try {
      const blob = await adminApi.downloadB2BInvoice(id);
      const url = window.URL.createObjectURL(new Blob([blob]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `invoice-${invoiceNumber}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
    } catch (error) {
      console.error('Download failed', error);
      alert('Failed to download invoice. Please try again.');
    }
  };

  if (isLoading) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary-500" />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-black tracking-tight text-slate-900">Company Invoices</h1>
        <p className="mt-2 text-slate-500">View and download B2B invoices generated by Vaniki Crop for your store.</p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {data?.data && data.data.length > 0 ? (
          data.data.map((invoice: any) => (
            <div
              key={invoice._id}
              className="group relative overflow-hidden rounded-[2rem] border border-primary-100 bg-white p-6 shadow-[0_8px_30px_rgba(0,0,0,0.04)] transition-all hover:shadow-[0_20px_50px_rgba(45,106,79,0.12)]"
            >
              <div className="flex items-start justify-between">
                <div className="rounded-2xl bg-primary-50 p-3 text-primary-600 transition-colors group-hover:bg-primary-500 group-hover:text-white">
                  <FileText size={24} />
                </div>
                <div className="text-right">
                  <p className="text-xs font-bold uppercase tracking-widest text-slate-400">Total Amount</p>
                  <p className="text-xl font-black text-slate-900">₹{invoice.totalAmount.toLocaleString('en-IN')}</p>
                </div>
              </div>

              <div className="mt-6 space-y-4">
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest text-slate-400">Invoice No.</p>
                  <p className="font-bold text-slate-900">{invoice.invoiceNumber}</p>
                </div>

                <div className="flex items-center gap-2 text-sm text-slate-500">
                  <Calendar size={14} className="text-primary-500" />
                  <span>{format(new Date(invoice.invoiceDate), 'PPP')}</span>
                </div>
              </div>

              <div className="mt-8 flex items-center justify-between">
                <div className="flex -space-x-2">
                   {/* Avatar placeholders or icons for items? Just a visual touch */}
                   <div className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-slate-100 text-[10px] font-bold text-slate-600">
                     {invoice.items?.length || 0}
                   </div>
                   <span className="ml-4 self-center text-xs font-medium text-slate-500">Items included</span>
                </div>

                <button
                  onClick={() => handleDownload(invoice._id, invoice.invoiceNumber)}
                  className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white shadow-lg transition-all hover:bg-primary-600 hover:shadow-primary-500/25 active:scale-95"
                >
                  <Download size={16} />
                  Download
                </button>
              </div>

              {/* Decorative background element */}
              <div className="absolute -bottom-6 -right-6 h-24 w-24 rounded-full bg-primary-50 opacity-0 transition-opacity group-hover:opacity-100" />
            </div>
          ))
        ) : (
          <div className="col-span-full flex flex-col items-center justify-center rounded-[3rem] border-2 border-dashed border-slate-200 bg-slate-50/50 py-20 text-center">
            <div className="mb-4 rounded-full bg-white p-6 shadow-xl">
              <FileText size={48} className="text-slate-300" />
            </div>
            <h3 className="text-lg font-bold text-slate-900">No invoices found</h3>
            <p className="mt-2 text-slate-500">Your B2B invoices will appear here once generated by the platform.</p>
          </div>
        )}
      </div>
    </div>
  );
}
