version: '3.8'

services:
  vaniki-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaniki-api
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
